//! Verify the crate against scikit-hep `particle` (the oracle). The fixtures
//! `oracle_cases.rs` and `particle_cases.rs` are GENERATED by
//! `scripts/gen_particle.py` from the `particle` package; here we replay them
//! and assert every PDG-ID decoding and every derived particle quantity matches.

use oxiroot_particle::{Particle, PdgId};

#[allow(missing_docs)] // generated fixtures — the fields document themselves
#[path = "fixtures/oracle_cases.rs"]
mod oracle_cases;
#[allow(missing_docs)]
#[path = "fixtures/particle_cases.rs"]
mod particle_cases;

use oracle_cases::{Case, CASES, NONE, PRED_NAMES};
use particle_cases::{PCase, NONE_I, PARTICLE_CASES};

/// Evaluate a named predicate on a `PdgId` — the mapping mirrors the order the
/// generator wrote into `PRED_NAMES` / `Case::preds`.
fn eval_pred(name: &str, id: PdgId) -> bool {
    match name {
        "is_valid" => id.is_valid(),
        "is_quark" => id.is_quark(),
        "is_sm_quark" => id.is_sm_quark(),
        "is_lepton" => id.is_lepton(),
        "is_sm_lepton" => id.is_sm_lepton(),
        "is_meson" => id.is_meson(),
        "is_baryon" => id.is_baryon(),
        "is_hadron" => id.is_hadron(),
        "is_diquark" => id.is_diquark(),
        "is_nucleus" => id.is_nucleus(),
        "is_pentaquark" => id.is_pentaquark(),
        "is_gauge_boson_or_higgs" => id.is_gauge_boson_or_higgs(),
        "is_sm_gauge_boson_or_higgs" => id.is_sm_gauge_boson_or_higgs(),
        "is_generator_specific" => id.is_generator_specific(),
        "is_special_particle" => id.is_special_particle(),
        "is_r_hadron" => id.is_r_hadron(),
        "is_qball" => id.is_qball(),
        "is_dyon" => id.is_dyon(),
        "is_susy" => id.is_susy(),
        "is_technicolor" => id.is_technicolor(),
        "is_excited_quark_or_lepton" => id.is_excited_quark_or_lepton(),
        "has_down" => id.has_down(),
        "has_up" => id.has_up(),
        "has_strange" => id.has_strange(),
        "has_charm" => id.has_charm(),
        "has_bottom" => id.has_bottom(),
        "has_top" => id.has_top(),
        "has_fundamental_anti" => id.has_fundamental_anti(),
        other => panic!("unmapped predicate in fixture: {other}"),
    }
}

fn opt_i32(v: i64) -> Option<i32> {
    if v == NONE {
        None
    } else {
        Some(v as i32)
    }
}

#[test]
fn pdgid_decoding_matches_scikit_hep() {
    assert!(!CASES.is_empty() && !PRED_NAMES.is_empty());
    let mut checked = 0usize;
    for &Case {
        id,
        preds,
        three_charge,
        j_spin,
        s_spin,
        l_spin,
        a,
        z,
    } in CASES
    {
        let pid = PdgId::new(id);
        for (i, &name) in PRED_NAMES.iter().enumerate() {
            let expected = (preds >> i) & 1 == 1;
            assert_eq!(eval_pred(name, pid), expected, "{name}({id}) mismatch");
        }
        assert_eq!(
            pid.three_charge(),
            opt_i32(three_charge),
            "three_charge({id})"
        );
        assert_eq!(pid.j_spin(), opt_i32(j_spin), "j_spin({id})");
        assert_eq!(pid.s_spin(), opt_i32(s_spin), "s_spin({id})");
        assert_eq!(pid.l_spin(), opt_i32(l_spin), "l_spin({id})");
        assert_eq!(pid.a(), opt_i32(a), "A({id})");
        assert_eq!(pid.z(), opt_i32(z), "Z({id})");
        checked += 1;
    }
    assert!(checked > 600, "expected the full table, got {checked}");
}

fn approx(got: Option<f64>, want: f64, ctx: &str) {
    if want.is_nan() {
        assert!(got.is_none(), "{ctx}: expected None, got {got:?}");
        return;
    }
    let g = got.unwrap_or_else(|| panic!("{ctx}: expected Some({want}), got None"));
    if want.is_infinite() {
        assert!(
            g.is_infinite() && g.signum() == want.signum(),
            "{ctx}: {g} vs inf"
        );
        return;
    }
    let tol = 1e-6 * want.abs().max(1.0);
    assert!((g - want).abs() <= tol, "{ctx}: {g} vs {want}");
}

#[test]
fn particle_properties_match_scikit_hep() {
    for &PCase {
        id,
        name,
        mass,
        three_charge,
        lifetime_ns,
        ctau_mm,
    } in PARTICLE_CASES
    {
        let p = Particle::from_pdgid(id)
            .unwrap_or_else(|| panic!("particle {id} ({name}) missing from the table"));
        assert_eq!(p.name(), name, "name({id})");
        approx(p.mass(), mass, &format!("mass({id})"));
        let tc = if three_charge == NONE_I {
            None
        } else {
            Some(three_charge as i32)
        };
        assert_eq!(p.three_charge(), tc, "three_charge({id})");
        approx(p.lifetime(), lifetime_ns, &format!("lifetime({id})"));
        approx(p.ctau(), ctau_mm, &format!("ctau({id})"));
    }
}

#[test]
fn lookups_and_invert() {
    // Round-trip a few well-known particles by id and by name.
    let proton = Particle::from_pdgid(2212).unwrap();
    assert_eq!(proton.name(), "p");
    assert_eq!(Particle::from_name("p").unwrap().pdg_id(), 2212);

    // A self-conjugate particle inverts to itself; a charged one flips sign.
    let z = Particle::from_pdgid(23).unwrap();
    assert!(z.is_self_conjugate());
    assert_eq!(z.invert().unwrap().pdg_id(), 23);

    let pip = Particle::from_pdgid(211).unwrap();
    assert!(!pip.is_self_conjugate());
    assert_eq!(pip.invert().unwrap().pdg_id(), -211);
    assert_eq!(pip.invert().unwrap().charge(), Some(-1.0));

    // Neutrino: convenience predicate + unknown mass.
    let nu = PdgId::new(12);
    assert!(nu.is_neutrino() && nu.is_lepton());
    assert_eq!(Particle::from_pdgid(12).unwrap().mass(), None);

    assert!(Particle::count() > 600);
}
