#!/usr/bin/env python3
"""Generate the coefficient table for Temme's uniform asymptotic expansion of
the regularized incomplete gamma functions (pure Python, standard library only).

    python3 scripts/gen_temme_coeffs.py > crates/oxiroot-stat/src/special/temme.rs

The expansion (DLMF 8.12) writes, with lambda = x/a and eta the signed root of
eta^2/2 = lambda - 1 - ln(lambda),

    Q(a, x) = erfc(eta sqrt(a/2)) / 2 + exp(-a eta^2/2) / sqrt(2 pi a) * S,
    P(a, x) = erfc(-eta sqrt(a/2)) / 2 - exp(-a eta^2/2) / sqrt(2 pi a) * S,
    S       = sum_k c_k(eta) a^-k,    c_k(eta) = sum_n D[k][n] eta^n.

The first coefficients come from c_0(eta) = 1/(lambda - 1) - 1/eta; the rest
follow from DLMF's recurrence, which in terms of the power-series coefficients
reads

    D[k][n] = (-1)^k gamma_k D[0][n] + (n + 2) D[k-1][n+2],

where gamma_k are the coefficients of Gamma*(a) = sum_k gamma_k a^-k (Stirling's
series). Every coefficient is computed exactly as a fraction and rounded once
to the nearest double.
"""

from fractions import Fraction as F

K = 25  # terms in a^-k
N = 25  # terms in eta^n
ORDER = N + 2 * (K - 1) + 2  # D[0] is needed up to n = N - 1 + 2 (K - 1)


def bernoulli(nmax):
    """B_0 .. B_nmax exactly, with B_1 = -1/2."""
    b = []
    for m in range(nmax + 1):
        a = [F(1, j + 1) for j in range(m + 1)]
        for j in range(m, 0, -1):
            for i in range(j):
                a[i] = (i + 1) * (a[i] - a[i + 1])
        b.append(a[0])
    b[1] = -b[1]  # the Akiyama-Tanigawa algorithm gives B_1 = +1/2
    return b


def mul(a, b, n):
    """The product of two power series, truncated to n terms."""
    out = [F(0)] * n
    for i, ai in enumerate(a[:n]):
        if ai:
            for j, bj in enumerate(b[: n - i]):
                out[i + j] += ai * bj
    return out


def reciprocal(a, n):
    """1/a for a power series with a[0] != 0."""
    r = [F(0)] * n
    r[0] = 1 / a[0]
    for k in range(1, n):
        r[k] = -sum(a[i] * r[k - i] for i in range(1, min(k, len(a) - 1) + 1)) / a[0]
    return r


def sqrt1(a, n):
    """sqrt of a power series with a[0] == 1."""
    s = [F(1)] + [F(0)] * (n - 1)
    for k in range(1, n):
        s[k] = (a[k] - sum(s[i] * s[k - i] for i in range(1, k))) / 2
    return s


def exp_series(l, n):
    """exp of a power series with l[0] == 0."""
    e = [F(1)] + [F(0)] * (n - 1)
    for k in range(1, n):
        e[k] = sum(j * l[j] * e[k - j] for j in range(1, k + 1)) / k
    return e


def gammastar(n):
    """gamma_0 .. gamma_{n-1}, with Gamma*(a) = sum_k gamma_k a^-k."""
    b = bernoulli(2 * n)
    log = [F(0)] * n  # ln Gamma*(a) = sum_j B_2j / (2j (2j - 1)) a^(1 - 2j)
    for j in range(1, n):
        if 2 * j - 1 < n:
            log[2 * j - 1] = b[2 * j] / (2 * j * (2 * j - 1))
    return exp_series(log, n)


def lambda_minus_one(n):
    """mu = lambda - 1 as a power series in eta, by Lagrange inversion of
    eta = mu h(mu), h(mu) = sqrt(2 (mu - ln(1 + mu)) / mu^2)."""
    # 2 (mu - ln(1 + mu)) / mu^2 = sum_m 2 (-1)^m mu^m / (m + 2)
    h = sqrt1([F(2 * (-1) ** m, m + 2) for m in range(n + 1)], n + 1)
    g = reciprocal(h, n + 1)
    mu = [F(0)] * (n + 1)
    power = [F(1)] + [F(0)] * n
    for k in range(1, n + 1):
        power = mul(power, g, n + 1)
        mu[k] = power[k - 1] / k  # [eta^k] mu = [mu^(k-1)] g^k / k
    return mu


def coefficients():
    mu = lambda_minus_one(ORDER + 2)
    # 1/mu = (1/eta) / (mu/eta), so c_0 = 1/mu - 1/eta has the coefficients of
    # the reciprocal of mu/eta, shifted by one.
    recip = reciprocal([mu[k + 1] for k in range(ORDER + 1)], ORDER + 1)
    d0 = [recip[n + 1] for n in range(ORDER)]
    gam = gammastar(K + 1)
    d = [d0]
    for k in range(1, K):
        sign = -1 if k % 2 else 1
        prev = d[k - 1]
        d.append([sign * gam[k] * d0[n] + (n + 2) * prev[n + 2] for n in range(len(prev) - 2)])

    # Values derived by hand (and printed in DLMF and Temme's paper).
    assert gam[:5] == [F(1), F(1, 12), F(1, 288), F(-139, 51840), F(-571, 2488320)]
    assert d[0][:6] == [F(-1, 3), F(1, 12), F(-2, 135), F(1, 864), F(1, 2835), F(-139, 777600)]
    assert d[1][:3] == [F(-1, 540), F(-1, 288), F(1, 378)]
    return d


def main():
    d = coefficients()
    print("//! Coefficients of Temme's uniform asymptotic expansion of the regularized")
    print("//! incomplete gamma functions (DLMF 8.12): `c_k(η) = Σ_n D[k][n] ηⁿ`.")
    print("//!")
    print("//! Generated by `scripts/gen_temme_coeffs.py`, which computes each coefficient")
    print("//! exactly as a fraction and rounds it once to `f64`. Do not edit by hand.")
    print()
    print("/// `D[k][n]`: the coefficient of `ηⁿ` in `c_k(η)`.")
    print(f"pub(super) const D: [[f64; {N}]; {K}] = [")
    for k in range(K):
        print("    [")
        for n in range(N):
            print(f"        {float(d[k][n])!r},")
        print("    ],")
    print("];")


if __name__ == "__main__":
    main()
