// Minimal self-contained JSON reader for the interop matrix manifest.
//
// The manifest is machine-generated by crates/oxiroot/examples/interop_matrix.rs
// (well-formed, ASCII, no surrogate pairs), so a tiny recursive-descent parser
// is enough — we avoid vendoring a ~900 KB single-header library for it. Numbers
// are parsed with strtod (handles ints, decimals, and exponents like 1e-9).
//
// Usage:
//   jsonm::Value m = jsonm::parse(read_file("manifest.json"));
//   for (const jsonm::Value& c : m["cases"].arr) { c["id"].str; c["dim"].num; }

#ifndef OXIROOT_JSON_MINI_HPP
#define OXIROOT_JSON_MINI_HPP

#include <cstdlib>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace jsonm {

struct Value {
  enum Type { Null, Bool, Num, Str, Arr, Obj } type = Null;
  bool b = false;
  double num = 0.0;
  std::string str;
  std::vector<Value> arr;
  std::vector<std::pair<std::string, Value>> obj;

  bool is_null() const { return type == Null; }
  bool as_bool() const { return b; }
  double as_num() const { return num; }
  long long as_int() const { return static_cast<long long>(num); }
  const std::string& as_str() const { return str; }
  size_t size() const { return type == Arr ? arr.size() : obj.size(); }

  // Object member access; returns a static Null on miss.
  bool has(const std::string& k) const {
    for (auto& kv : obj)
      if (kv.first == k) return true;
    return false;
  }
  const Value& operator[](const std::string& k) const {
    static const Value null_value;
    for (auto& kv : obj)
      if (kv.first == k) return kv.second;
    return null_value;
  }
  const Value& operator[](size_t i) const { return arr[i]; }
};

class Parser {
 public:
  explicit Parser(const std::string& s) : s_(s) {}
  Value parse() {
    Value v = value();
    skip_ws();
    return v;
  }

 private:
  const std::string& s_;
  size_t i_ = 0;

  [[noreturn]] void fail(const char* msg) {
    throw std::runtime_error(std::string("json parse error at ") +
                             std::to_string(i_) + ": " + msg);
  }
  void skip_ws() {
    while (i_ < s_.size()) {
      char c = s_[i_];
      if (c == ' ' || c == '\t' || c == '\n' || c == '\r')
        i_++;
      else
        break;
    }
  }
  char peek() {
    skip_ws();
    if (i_ >= s_.size()) fail("unexpected end");
    return s_[i_];
  }

  Value value() {
    char c = peek();
    switch (c) {
      case '{': return object();
      case '[': return array();
      case '"': { Value v; v.type = Value::Str; v.str = string(); return v; }
      case 't': case 'f': return boolean();
      case 'n': { expect_lit("null"); Value v; v.type = Value::Null; return v; }
      default: return number();
    }
  }

  void expect_lit(const char* lit) {
    for (const char* p = lit; *p; ++p) {
      if (i_ >= s_.size() || s_[i_] != *p) fail("bad literal");
      i_++;
    }
  }

  Value boolean() {
    Value v;
    v.type = Value::Bool;
    if (peek() == 't') {
      expect_lit("true");
      v.b = true;
    } else {
      expect_lit("false");
      v.b = false;
    }
    return v;
  }

  Value number() {
    skip_ws();
    const char* start = s_.c_str() + i_;
    char* end = nullptr;
    double d = std::strtod(start, &end);
    if (end == start) fail("bad number");
    i_ += static_cast<size_t>(end - start);
    Value v;
    v.type = Value::Num;
    v.num = d;
    return v;
  }

  std::string string() {
    if (peek() != '"') fail("expected string");
    i_++;  // opening quote
    std::string out;
    while (i_ < s_.size()) {
      char c = s_[i_++];
      if (c == '"') return out;
      if (c == '\\') {
        if (i_ >= s_.size()) fail("bad escape");
        char e = s_[i_++];
        switch (e) {
          case '"': out.push_back('"'); break;
          case '\\': out.push_back('\\'); break;
          case '/': out.push_back('/'); break;
          case 'n': out.push_back('\n'); break;
          case 't': out.push_back('\t'); break;
          case 'r': out.push_back('\r'); break;
          case 'b': out.push_back('\b'); break;
          case 'f': out.push_back('\f'); break;
          case 'u': {
            if (i_ + 4 > s_.size()) fail("bad \\u");
            int cp = std::stoi(s_.substr(i_, 4), nullptr, 16);
            i_ += 4;
            if (cp < 0x80) {
              out.push_back(static_cast<char>(cp));
            } else if (cp < 0x800) {
              out.push_back(static_cast<char>(0xC0 | (cp >> 6)));
              out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
            } else {
              out.push_back(static_cast<char>(0xE0 | (cp >> 12)));
              out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
              out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
            }
            break;
          }
          default: fail("unknown escape");
        }
      } else {
        out.push_back(c);
      }
    }
    fail("unterminated string");
  }

  Value array() {
    Value v;
    v.type = Value::Arr;
    i_++;  // '['
    if (peek() == ']') {
      i_++;
      return v;
    }
    while (true) {
      v.arr.push_back(value());
      char c = peek();
      if (c == ',') {
        i_++;
        continue;
      }
      if (c == ']') {
        i_++;
        break;
      }
      fail("expected , or ]");
    }
    return v;
  }

  Value object() {
    Value v;
    v.type = Value::Obj;
    i_++;  // '{'
    if (peek() == '}') {
      i_++;
      return v;
    }
    while (true) {
      std::string key = string();
      if (peek() != ':') fail("expected :");
      i_++;
      v.obj.emplace_back(std::move(key), value());
      char c = peek();
      if (c == ',') {
        i_++;
        continue;
      }
      if (c == '}') {
        i_++;
        break;
      }
      fail("expected , or }");
    }
    return v;
  }
};

inline Value parse(const std::string& text) { return Parser(text).parse(); }

}  // namespace jsonm

#endif  // OXIROOT_JSON_MINI_HPP
